<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<diagram program="umlet" version="11.5">
  <zoom_level>10</zoom_level>
  <element>
    <type>com.umlet.element.Class</type>
    <coordinates>
      <x>230</x>
      <y>210</y>
      <w>160</w>
      <h>80</h>
    </coordinates>
    <panel_attributes>Director
--
--
Construct()</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <type>com.umlet.element.Class</type>
    <coordinates>
      <x>560</x>
      <y>210</y>
      <w>160</w>
      <h>70</h>
    </coordinates>
    <panel_attributes>/Builder/
--
--
/+BuildPart()/</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <type>com.umlet.element.Class</type>
    <coordinates>
      <x>560</x>
      <y>410</y>
      <w>160</w>
      <h>70</h>
    </coordinates>
    <panel_attributes>/ConcreteBuilder/
--
--
+BuildPart()
+GetResult()
</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <type>com.umlet.element.Relation</type>
    <coordinates>
      <x>610</x>
      <y>250</y>
      <w>50</w>
      <h>180</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;-</panel_attributes>
    <additional_attributes>30;30;30;160</additional_attributes>
  </element>
  <element>
    <type>com.umlet.element.Class</type>
    <coordinates>
      <x>850</x>
      <y>430</y>
      <w>100</w>
      <h>30</h>
    </coordinates>
    <panel_attributes>Product</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <type>com.umlet.element.Relation</type>
    <coordinates>
      <x>690</x>
      <y>420</y>
      <w>180</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;&lt;&lt;&lt;.</panel_attributes>
    <additional_attributes>160;30;30;30</additional_attributes>
  </element>
  <element>
    <type>com.umlet.element.Note</type>
    <coordinates>
      <x>220</x>
      <y>380</y>
      <w>180</w>
      <h>80</h>
    </coordinates>
    <panel_attributes>for all object in structure{
    builder-&gt;BuildPart()
}
</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <type>com.umlet.element.Relation</type>
    <coordinates>
      <x>280</x>
      <y>260</y>
      <w>50</w>
      <h>140</h>
    </coordinates>
    <panel_attributes>lt=&lt;.</panel_attributes>
    <additional_attributes>30;30;30;120</additional_attributes>
  </element>
  <element>
    <type>com.umlet.element.Relation</type>
    <coordinates>
      <x>360</x>
      <y>220</y>
      <w>220</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;&lt;&lt;&lt;-&gt;&gt;&gt;
m2=builder</panel_attributes>
    <additional_attributes>200;30;30;30</additional_attributes>
  </element>
</diagram>
